### PR TITLE
Improve action context

### LINKED ISSUE #40: Gesture with window context
Hi, thank you for building this interesting plugin.
I'm not sure how to build a gesture that would depend on window location, would something like the following be possible?
* start dragging in a window, this will be the source
* release the mouse in a new window, this is the target
* swap the two windows

Example if I have the following window layout:
```
    │     │  C  
 A  │  B  │─────
    │     │  D
```
I'd like to click and drag from A to D, and end up with:
```
    │     │  C  
 D  │  B  │─────
    │     │  A
```

### PR DESCRIPTION
**Pull request by notomo**
fix: https://github.com/notomo/gesture.nvim/issues/40

### CODE REVIEW

**Comment by notomo** [comment]
## window swap demo 🚀


https://github.com/notomo/gesture.nvim/assets/18519692/ecfbbcb8-05f6-4014-bf74-19c189564a80



```lua
local swap = function(first_window_id, last_window_id)
  local first_window_view = vim.api.nvim_win_call(first_window_id, function()
    return vim.fn.winsaveview()
  end)
  local first_bufnr = vim.api.nvim_win_get_buf(first_window_id)

  local last_window_view = vim.api.nvim_win_call(last_window_id, function()
    return vim.fn.winsaveview()
  end)
  local last_bufnr = vim.api.nvim_win_get_buf(last_window_id)

  vim.api.nvim_win_set_buf(first_window_id, last_bufnr)
  vim.api.nvim_win_call(first_window_id, function()
    vim.fn.winrestview(last_window_view)
  end)

  vim.api.nvim_win_set_buf(last_window_id, first_bufnr)
  vim.api.nvim_win_call(last_window_id, function()
    vim.fn.winrestview(first_window_view)
  end)
end

local gesture = require("gesture")

gesture.register({
  name = "swap",
  match = function(ctx)
    return ctx.window_ids[1] ~= ctx.window_ids[#ctx.window_ids]
  end,
  can_match = function(ctx)
    return #ctx.window_ids >= 2
  end,
  action = function(ctx)
    local first_window_id = ctx.window_ids[1]
    local last_window_id = ctx.window_ids[#ctx.window_ids]
    swap(first_window_id, last_window_id)
    vim.api.nvim_set_current_win(last_window_id)
  end,
})
```

**Comment by notomo** [comment]
@m3at 
merged!
feedback is welcome.

**Comment by m3at** [comment]
Thanks, working great! 

It's a bit of a tangential question, but as I couldn't figure it out yet please allow me to ask in case you know 🙏:
How could I set a mapping that depends on key+drag? If I set something like `<Leader><LeftDrag>` it starts but requires an extra click to stop
```lua
vim.keymap.set("n", "<Leader><LeftDrag>", [[<Cmd>lua require("gesture").draw()<CR>]], { silent = true })
```

**Comment by notomo** [comment]
Unfortunately, I'm not sure.
I've not used with key + drag mapping.

Possibly, it is recognized as `<Leader><LeftRelease>` and `<LeftRelease>` is recognized on the next click.
If so, the following does work maybe.

```lua
vim.keymap.set("n", "<Leader><LeftRelease>", [[<Cmd>lua require("gesture").finish()<CR>]], { silent = true })
```

**Comment by m3at** [comment]
That doesn't appear to suffice unfortunately; I might try to dig into this later.
Thanks regardless!

**Pull request merged**
